import Theme from "@/app/_config/theme";
import AuthProvider from "@/app/AuthProvider";
import { ThemeProvider } from "flowbite-react";
import { Toaster } from "react-hot-toast";

import "@/app/_css/index.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={Theme}>
          <Toaster />
          <AuthProvider>{children}</AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
